In [5]:
# importing packages
import numpy as np
import pandas as pd
import scipy.stats as stats
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

data = pd.read_csv('./Data/train_clean.csv')

train = pd.read_csv('./Data/train_clean_split.csv')
test = pd.read_csv('./Data/test_clean_split.csv')

x_train = train[['sex', 'age', 'high_BP_2', 'heart_condition_detected_2017_2', 'married_2', 'average_blood_sugar_2', 'BMI_3', 'smoker_status_2', 'treated']].copy()
y_train = train[['stroke_in_2018']].copy()

x_test = test[['sex', 'age', 'high_BP_2', 'heart_condition_detected_2017_2', 'married_2', 'average_blood_sugar_2', 'BMI_3', 'smoker_status_2', 'treated']].copy()
y_test = test[['stroke_in_2018']].copy()

In [32]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn import metrics

def run_model(algo_name):
    algos = {'lr': LogisticRegressionCV(), 'knn': KNeighborsClassifier(n_neighbors =10), 'svm': svm.SVC()}
    algo = algos[algo_name]
    algo.fit(x_train, y_train)
    pred_train_lr = algo.predict(x_train)
    print(round(metrics.accuracy_score(y_train, pred_train_lr) * 100, 2))
    print(metrics.confusion_matrix(y_train, pred_train_lr))
    print()

    pred_test_lr = algo.predict(x_test)
    print(round(metrics.accuracy_score(y_test, pred_test_lr) * 100, 2))
    print(pred_test_lr.sum())
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, pred_test_lr).ravel()
    print(tn, fp, fn, tp)
    print(metrics.f1_score(y_test, pred_test_lr, average='binary'))

run_model('lr')
run_model('knn')
run_model('svm')

c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of it

98.12
[[23858     0]
 [  457     0]]

98.15
0
10217 0 193 0
0.0


c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':


98.12
[[23858     0]
 [  457     0]]

98.15
0
10217 0 193 0
0.0


c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


98.12
[[23858     0]
 [  457     0]]

98.15
0
10217 0 193 0
0.0


c:\users\danie\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
